server:
  port: 8006
spring:
  application:
    name: mongddb-service
  data:
    mongodb:
     uri: mongodb://admin:admin123@192.168.206.132:27017/test?authSource=admin
     authentication-database: test