server:
  port: 8005
spring:
  kafka:
    producer:
      batch-size: 16384
      retries: 0
      buffer-memory: 33554432
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
    bootstrap-servers: 192.168.206.131:9092
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: test-consumer-group
      auto-offset-reset: earliest
      auto-commit-interval: 100
      enable-auto-commit: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
